#!/bin/sh
# Install all dotfiles into the home directory
# Copy/Pasted/Modified 9/14/18 from https://github.com/MikeMcQuaid/dotfiles/blob/master/script/setup

DOTFILESDIRREL=$(dirname "$0")
cd "$DOTFILESDIRREL/.." || exit
DOTFILESDIR=$(pwd -P)

VSCODE="$HOME/Library/Application Support/Code/User"

for DOTFILE in *; do
  HOMEFILE="$HOME/.$DOTFILE"
  [ -d "$DOTFILE" ] && DOTFILE="$DOTFILE/"
  DIRFILE="$DOTFILESDIR/$DOTFILE"

  echo "$DOTFILE" | grep -Eq '(^script/$|\.txt$|\.md$)' && continue

  echo "$DOTFILE" | grep -q 'vscode-settings' &&
       HOMEFILE="$VSCODE/settings.json" &&
       mkdir -p "$VSCODE"

  echo "$DOTFILE" | grep -q '\.sh' &&
       HOMEFILE="$HOME/.$(echo $DOTFILE | sed -e 's/\.sh//')"

  if [ -L "$HOMEFILE" ] && ! [ -d "$DOTFILE" ]
  then
    ln -sfv "$DIRFILE" "$HOMEFILE"
  else
    rm -rv "$HOMEFILE"
    ln -sv "$DIRFILE" "$HOMEFILE"
  fi
done
